### ISSUE TITLE
Dialog doesn' t show

### ISSUE THREAD

**Issue by nailmed** [ItzNotABug/HouseAds#9]
Hello. Thank you for this library ,dialog  doesn't show and I don't get any error messages in logcat. i use the same code in  exemple :

`HouseAdsDialog houseAds = new HouseAdsDialog(RingtonesActivity.this, "https://api.myjson.com/bins/15dehw"); .
		houseAds.hideIfAppInstalled(false); 
		houseAds.setCardCorners(80); 
		houseAds.setCtaCorner(80); 
		houseAds.setForceLoadFresh(true);
		houseAds.showHeaderIfAvailable(true); 
		houseAds.loadAds();`

my json is : 

`{
  "apps": [
    {
      "app_title": "Kawaii Cats Wallpapers (Dialog)",
      "app_desc": "Kawaii Cats Wallpapers - Cute wallpapers",
      "app_icon": "https://funnyjokes.me/kawai/icon_play.png",
      "app_header_image": "https://funnyjokes.me/kawai/cover.png",
      "app_uri": "https://play.google.com/store/apps/details?id=com.CuteWallpaper.KawaiiCat",
      "app_rating": "5",
      "app_cta_text": "Install",
      "app_price": "Free",
      "app_adType": "dialog"
    },
    {
      "app_interstitial_url": "https://funnyjokes.me/kawai/icon_play.png",
      "app_uri": "https://play.google.com/store/apps/details?id=com.CuteWallpaper.KawaiiCat",
      "app_adType": "interstitial"
    },
    {
      "app_title": "Kawaii Cats Wallpapers (Native Ad)",
      "app_desc": "Kawaii Cats Wallpapers - Cute wallpapers",
      "app_icon": "https://funnyjokes.me/kawai/icon_play.png",
      "app_header_image": "https://funnyjokes.me/kawai/cover.png",
      "app_uri": "https://play.google.com/store/apps/details?id=com.CuteWallpaper.KawaiiCat",
      "app_rating": "4.5",
      "app_cta_text": "Install",
      "app_price": "Free",
      "app_adType": "native"
    }
  ]
}`

**Comment by ItzNotABug** [comment]
tried calling `houseAds.showAd();` ?

**Comment by nailmed** [comment]
i used `houseAds.showAd();` and still not working !!

**Comment by ItzNotABug** [comment]
I tried using your json file & it works as expected..
![](https://i.imgur.com/84lfQkv.png)

How & when are you calling `houseAds.showAd();` ?

**Comment by nailmed** [comment]
in `onCreate` function

**Comment by ItzNotABug** [comment]
You should use a listener..
Check the [ReadMe](https://github.com/ItzNotABug/HouseAds/blob/master/README.md#houseadsdialog) again for instructions..

**Comment by nailmed** [comment]
i added `setAdListener` and display this error

![Untitled](https://user-images.githubusercontent.com/50248575/57178485-9f503a00-6e68-11e9-93fc-9de89d9ac87c.png)

**Comment by ItzNotABug** [comment]
use like this,
houseAds.setAdListener(new com.lazygeniouz.house.ads.listener.AdListener() {
    @Override
    public void onAdLoadFailed() {}
    
    @Override
    public void onAdLoaded() {
        //Show AdDialog as soon as it is loaded.
        houseAds.showAd();
    }
             
    @Override
    public void onAdClosed() {}
    
    @Override
    public void onAdShown() {}
     
    @Override
    public void onApplicationLeft() {}
});

**Comment by ItzNotABug** [comment]
use like this,
```
houseAds.setAdListener(new com.lazygeniouz.house.ads.listener.AdListener() {
@Override
public void onAdLoaded() {
    houseAds.showAd();
}}); 
```

**Comment by nailmed** [comment]
![Untitled2222222222](https://user-images.githubusercontent.com/50248575/57178674-2357f100-6e6c-11e9-9680-47efc98644e6.png)

**Comment by ItzNotABug** [comment]
just implement all the methods!
